#!/usr/bin/env ruby

require 'cite_trans'
require 'jpts_extractor'

puts "#{ARGV[0]} #{ARGV[1]}"

file = File.open("#{ARGV[0]}")
article = CiteTrans.translate! file

puts JPTSExtractor.output(article)
